const cancionesQueen = [
  {
    idTrack: '32802697',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401345',
    idIMVDB: null,
    strTrack: 'Death on Two Legs (Dedicated to...)',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '223733',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '1',
    intLoved: '0',
    intScore: null,
    intScoreVotes: null,
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: 'a46d027a-39e0-4b47-b19b-bb7682839ac5',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802698',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401349',
    idIMVDB: null,
    strTrack: 'Lazing on a Sunday Afternoon',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '67426',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '2',
    intLoved: '0',
    intScore: '10',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: 'a69ca3a1-65ff-491a-b25e-fa2010963e26',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802699',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401348',
    idIMVDB: null,
    strTrack: "I'm in Love With My Car",
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '185440',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: 'Rudi Dolezal',
    strMusicVidCompany: '',
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '3',
    intLoved: '0',
    intScore: '10',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: '8c8cc498-39e7-440f-b937-21d1481cc3a0',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802700',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401354',
    idIMVDB: null,
    strTrack: "You're My Best Friend",
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '172666',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '4',
    intLoved: '0',
    intScore: '9',
    intScoreVotes: '3',
    intTotalListeners: '657216',
    intTotalPlays: '3167455',
    strMusicBrainzID: '471dc436-80be-4f06-bc8f-7e2685876cfc',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802701',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401343',
    idIMVDB: null,
    strTrack: "'39",
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '211000',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '5',
    intLoved: '0',
    intScore: '5.5',
    intScoreVotes: '2',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: '16d2c90d-d688-4465-bb76-4a9e94b80729',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802702',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401352',
    idIMVDB: null,
    strTrack: 'Sweet Lady',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '244400',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '6',
    intLoved: '0',
    intScore: '6',
    intScoreVotes: '2',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: 'e787ac41-3aba-41b6-ad05-63ddb02b50b8',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802703',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401351',
    idIMVDB: null,
    strTrack: 'Seaside Rendezvous',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '136826',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '7',
    intLoved: '0',
    intScore: '4',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: 'e26a4230-72bf-4fbe-b86b-2f045ebb2cb7',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802704',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401353',
    idIMVDB: null,
    strTrack: "The Prophet's Song",
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '501466',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '8',
    intLoved: '0',
    intScore: '3',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: '1709306b-e1a4-471f-ab6d-6c78ab0a55be',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802705',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401350',
    idIMVDB: null,
    strTrack: 'Love of My Life',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '219240',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '9',
    intLoved: '0',
    intScore: '8',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: '1c289c49-9b7d-4123-b8c6-d3aafe16eb40',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802706',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401347',
    idIMVDB: null,
    strTrack: 'Good Company',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '203893',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '10',
    intLoved: '0',
    intScore: '3',
    intScoreVotes: '1',
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: 'd002ad96-7eac-4ca5-9b45-d89b8c7f15ee',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802707',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401344',
    idIMVDB: '0',
    strTrack: 'Bohemian Rhapsody',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '355106',
    strGenre: 'Rock',
    strMood: 'Rousing',
    strStyle: 'Rock/Pop',
    strTheme: '...',
    strDescriptionEN:
      '"Bohemian Rhapsody" is a song by the British rock band Queen. It was written by Freddie Mercury for the band\'s 1975 album A Night at the Opera. The song has no chorus, instead consisting of several sections: a ballad segment ending with a guitar solo, an operatic passage, and a hard rock section. At the time, it was the most expensive single ever made and it remains one of the most elaborate recordings in popular music history.',
    strTrackThumb:
      'https://www.theaudiodb.com/images/media/track/thumb/trvqxt1582885477.jpg',
    strTrack3DCase: null,
    strTrackLyrics: '',
    strMusicVid: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
    strMusicVidDirector: 'Bruce Gowers',
    strMusicVidCompany: 'Hollywood records',
    strMusicVidScreen1:
      'https://www.theaudiodb.com/images/media/track/mvidscreen/vxquvq1582885556.jpg',
    strMusicVidScreen2:
      'https://www.theaudiodb.com/images/media/track/mvidscreen/tsytup1582885566.jpg',
    strMusicVidScreen3:
      'https://www.theaudiodb.com/images/media/track/mvidscreen/vpyyuw1582885574.jpg',
    intMusicVidViews: '754654610',
    intMusicVidLikes: '4295822',
    intMusicVidDislikes: '151879',
    intMusicVidFavorites: '0',
    intMusicVidComments: '345587',
    intTrackNumber: '11',
    intLoved: '0',
    intScore: '9.5',
    intScoreVotes: '8',
    intTotalListeners: '1399221',
    intTotalPlays: '9723231',
    strMusicBrainzID: 'ebf79ba5-085e-48d2-9eb8-2d992fbf0f6d',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
  {
    idTrack: '32802708',
    idAlbum: '2116679',
    idArtist: '111238',
    idLyric: '401346',
    idIMVDB: null,
    strTrack: 'God Save the Queen',
    strAlbum: 'A Night at the Opera',
    strArtist: 'Queen',
    strArtistAlternate: null,
    intCD: null,
    intDuration: '75800',
    strGenre: 'Rock',
    strMood: null,
    strStyle: null,
    strTheme: null,
    strDescriptionEN: null,
    strTrackThumb: null,
    strTrack3DCase: null,
    strTrackLyrics: null,
    strMusicVid: null,
    strMusicVidDirector: null,
    strMusicVidCompany: null,
    strMusicVidScreen1: null,
    strMusicVidScreen2: null,
    strMusicVidScreen3: null,
    intMusicVidViews: null,
    intMusicVidLikes: null,
    intMusicVidDislikes: null,
    intMusicVidFavorites: null,
    intMusicVidComments: null,
    intTrackNumber: '12',
    intLoved: '0',
    intScore: null,
    intScoreVotes: null,
    intTotalListeners: null,
    intTotalPlays: null,
    strMusicBrainzID: '4112acb8-7ac0-4047-9c02-6e02226003e7',
    strMusicBrainzAlbumID: '6b47c9a0-b9e1-3df9-a5e8-50a6ce0dbdbd',
    strMusicBrainzArtistID: '0383dadf-2a4e-4d10-a46a-e9e041da8eb3',
    strLocked: 'unlocked',
  },
]
